#include<stdio.h>
int main(){
    int a,b,c,d,e,f;
    scanf("%d%d%d%d%d",&a,&b,&c,&d,&e);
    for(f=0;f<a;f++)
    {
        printf("*");
    }
    printf("\n");
    for(f=0;f<b;f++)
    {
        printf("*");
    }
    printf("\n");
    for(f=0;f<c;f++)
    {
        printf("*");
    }
    printf("\n");
    for(f=0;f<d;f++)
    {
        printf("*");
    }
    printf("\n");
    for(f=0;f<e;f++)
    {
        printf("*");
    }
    printf("\n");
}
